### ISSUE TITLE
proposals as lineage database

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#2745]
- [x] `git town set-parent` changes the proposal
- `git kill` 
  - [x] closes the proposal for the current branch
  - [x] updates the proposals of child branches to go against the parent branch
- [x] `git rename-branch` update the proposal so that it doesn't get closed
- [ ] if a branch has no known parent, look for an active proposal and use the base branch from that proposal as the parent.
- [x] `git prepend` updates the base branch of an existing proposal for the new parent to the newly created branch

This ticket also requires #3912

**Comment by kevgo** [comment]
A challenge with `rename-branch` is that pretty much all code hosting platforms (I have checked GitHub, GitLab, and BitBucket so far) cannot update the "head" or "source" branch of a pull request. This causes the PR of a renamed branch to close and the user needs to open a new PR that "supersedes" the old PR.

This is clearly not what the user wants, but it seems there is nothing Git Town can do about this.

Possible courses of action:

1. Just rename the branch and tell the user that they have to create a new PR for this branch.
2. Refuse to rename branches that have PRs.
3. Before renaming the branch, warn the user that renaming this branch will close the PR. Get confirmation from the user that it is okay to proceed.

**Comment by kevgo** [comment]
Went with renaming the branch and notifying the user that the PR is now closed because that's closest to doing what the user requested.

**Comment by kevgo** [comment]
A challenge with downloading the entire lineage on each sync is that if there are a lot of branches, it performs a lot of network requests, which would make the sync operation prohibitively slow.

Maybe it's better to only look for a proposal if the lineage for a branch isn't known at all.

**Comment by mw00120** [comment]
I have something worth noting that I believe is relevant to this ticket. In Bitbucket in particular (I haven't tested other platforms), if you _merge_ a pull request (so merge feature-1 into master) and you have other PRs actively open that are targetting feature-1, the UI prompts asking the user if they want to retarget their PRs...

To clarify:

PR1: feature-1 to master
PR2: feature-2 to feature-1

Merge PR1, prompt to retarget "affected pull requests".

PR2 is now feature-2 to master.

**Comment by stephenwade** [comment]
On GitHub, this happens automatically (PR2 is now feature-2 to master).

@mw00120 What happens if you say no? Are the other PRs closed?

**Comment by kevgo** [comment]
This is now available in [v16.3](https://github.com/git-town/git-town/releases/tag/v16.3.0).

**Comment by mw00120** [comment]
@stephenwade Here are the options:

![image](https://github.com/user-attachments/assets/ac85eda2-40c5-43c2-b709-b927bc5c1b04)

We have PR 1 merging `patch` into `epic`. We have another PR 2 merging `patch2` into `patch`.

1. You click the checkbox for PR 1: After the merge bitbucket deletes `patch` and retarges PR 2's target to `epic`.
2. You do not click the checkbox: The `patch` branch is not deleted and PR 2 remains `patch2` -> `patch`.

**By default, it is checked.**

My main concern would be if we're using a hybrid approach for merging stacks. This is allowed by the configuration "ship deletes tracking branch: no", which during the setup is suggested if "The code hosting platform is responsible for deleting branches after a merge". In this case if we merge these branches through the bitbucket UI I'm curious what will happen to the lineage database on the next sync...

I have the new version of git town (v16.3) installed, and I will likely be handling a merge of this type soon, so I can report a bug if there are issues :)

**Comment by kevgo** [comment]
You need to keep this checkbox checked.

When checked, Bitbucket will automatically delete the remote branch and retarget the PRs of any child branches. This allows `git sync` to detect that the remote branch has been deleted. Git Town will then remove the corresponding local branch and update the local branch hierarchy, making the child branches of the deleted branch inherit from the deleted branch's parent.

If you uncheck the box, Bitbucket will not delete the remote branch. In this case, when you run `git sync`, Git Town assumes the branch hasn’t been shipped and continues syncing it as usual. This results in a branch with no actual changes.

The planned [`--prune` switch for `git sync`](https://github.com/git-town/git-town/issues/2557) can detect and remove such empty branches, but this isn't implemented yet.

**Comment by mw00120** [comment]
Very interesting, thanks!
