### ISSUE TITLE
Advanced branch syncing

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3095]
Git Town's sync capabilities are a great fit for most developers. This ticket outlines support for important edge cases where one doesn't want to sync everything all the time. The goal is to make both `git sync` on a branch as well as `git sync --all` always do the right thing, so that people can use these commands liberally and fearlessly.

# Branch Types

### Feature Branch

The normal feature branch as it exists today. No changes to its behavior. I (the Git Town user) own this branch. The local branch exists so that I can develop a feature on it.

- when running `git sync` on this branch or `git sync --all`:
  - pull updates from parent
  - tracking: sync down and up, using the configured sync-feature-strategy
- prune if tracking branch is gone + no unshipped changes

### Parked branch

A feature branch that I own but don't work on right now, and don't want to spend time resolving merge conflicts because this branch is not important right now and I'm fully focused on another branch. 

- [x] when running `git sync` on this branch: sync the branch normally
  - pull updates from parent
  - tracking: down and up, using the configured sync-feature-strategy
  - prune if tracking branch is gone + no unshipped changes
- [x] when running `git sync --all`: don't sync this branch
  - don't pull updates from parent
  - don't pull updates from the tracking branch
  - if tracking branch is gone: `git sync --all` is not allowed to sync this branch locally, so it cannot determine whether it is safe to delete this branch or not. Therefore ask the user what to do:
     - delete the local branch
     - sync locally and delete if no unshipped changes
     - do nothing

You park a branch by running `git park` on the branch.

### Contribution branch

The branch on my machine exists so that I can contribute commits to a branch that somebody else owns. A possible scenario is I am a staff engineer and remote-support a junior developer with a problem the junior is working on. While remote pairing I sometimes enter the drivers seat. So I have the junior's branch on my machine and want it to stay in sync with the branch on the junior's machine. But I don't want to update the branch with updates from main. That's the responsibility of the person owning this branch.

- [x] when running `git sync` on this branch or `git sync --all`:
  - don't pull updates from parent
  - sync the tracking branch down and up, using the configured sync-feature-strategy
- [x] prune if tracking branch is gone, ignore unshipped changes
- [x] cannot create proposals for it
- [x] cannot ship it

You checkout a contributor branch by running `git contribute <branch name>` instead of `git checkout <branch name>`. You convert a branch that already exists on your machine into a contributor branch by running `git contribute` on this branch.

Contribution branches behave similar to perennial branches. The difference between them is that perennial branches are the same for everybody and can therefore be defined in the config file, while contribution branches are different for everybody and can therefore only be defined in Git metadata.

### Observed branch

This branch exists on my machine so that I can observe the work that somebody else is doing on their machine in a branch that person owns. I don't contribute commits to this branch. A possible scenario is I am a staff engineer and help a junior developer with a problem the junior is stuck on. I check out the junior's branch on my machine to try out a few things. But I want the junior to implement everything so that they learn by doing. My local changes should not be pushed up.

- [x] `git sync` on this branch or `git sync --all`
  - don't pull updates from parent
  - tracking: down only, rebase only
- [x] prune if tracking branch is gone, ignore unshipped changes
- [x] cannot create proposals for it
- [x] cannot ship it

You checkout an observer branch by running `git observe <branchname>` instead of `git checkout <branchname>`. You make a branch that already exists on your machine an observer branch by running `git observe` on the branch.

### Perennial branch

Nobody owns this branch, everybody just supports it.

- `git sync` or `git sync --all`:
  - don't pull updates from parent
  - tracking: down and up, rebase only
- prune if tracking branch is gone, ignore unshipped changes

# Configuration settings

- `auto-park`: all branches are parked by default
  - for people who always work one branch at a time
- `sync-frequency`: limits pulling in updates from the main branch to once a day/week/month/never. This is when pulling in updates is expensive.
  - this supports the monorepo use case

# Changing branch types

Via CLI commands that modify the current branch. When called without a branch argument, it changes the current branch. If these commands are called with a branch argument, and the branch exists, it checks out the given branch and changes it. If a branch with the given name doesn't exist, it creates a new feature branch and gives it the given property.

- [x] `git town park <branch names or regexes>`
- [x] `git town feature <branch names or regexes>`
- [x] `git town contribute <branch names or regexes>`
- [x] `git town observe <branch names or regexes>`

via hotkeys in `git town switch`:

- [ ] `p` makes the selected branch parked
- [ ] `o` makes the selected branch an observed branch
- [ ] `c` makes the selected branch a contribution branch
- [ ] `f` makes the selected branch a feature branch
- [ ] the hotkey to select a branch changes from `o` to `i`

### Combinations of attributes

The initial implementations has only one branch type per branch. This keeps the concept and implementation simple, straightforward, and understandable. A possible refinement for branch attributes is allowing to combine them. This comes at the cost of additional complexity of concept and implementation as well as a higher learing curve.

Here are the attribute combinations that make sense:
- perennial + parked
  - inactive: doesn't sync
  - active: syncs the perennial branch
- contribution + parked:
  - inactive: doesn't sync
  - active: 2-way sync with tracking branch
- observed + parked:
  - inactive: doesn't sync
  - active: 1-way sync from tracking branch

Here are the attribute combinations that are debatable:
- main + parked: doesn't pull in updates from the tracking branch unless the user runs `git sync` on the main branch
  - this is a poor-man solution for #2711
  - leaves the risk of the entire workspace falling out of sync undetected
  - probably better to implement #2711 instead of advising users to do this
- perennial + observed
  - doesn't push local updates
  - Might lead to hidden discrepancy between branches on people's workstations when somebody has a commit on a perennial branch that others don't. Perennial branches are supposed to stay in sync with the rest of the world.
  - might be useful for hacks

Here are the attribute combinations that don't make sense but also don't cause harm:

- perennial + contribution = perennial
- observed + contribution = observed

Here are the attribute combinations that cause harm:
