### ISSUE TITLE
more rebase/amend friendly tracking branch synchronization

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3182]
Right now `git sync` pulls commits from the tracking branch before pushing the updated local commits to the tracking branch. For example, the current steps to sync a feature branch named `branch` with a parent branch named `parent` are:

```fish
git rebase origin/branch      # rebase the local commits on top of new commits on the tracking branch
git rebase parent             # rebase the local commits on top of new commits on the parent branch
git push --force-with-lease   # push the updated branch to the tracking branch
```

This behavior makes sense for the `merge` sync-feature-strategy where everything can be properly merged via merge commits. It is incompatible with workflows that change existing commits, like amending or doing interactive rebases, because this sync behavior mixes old commits from the tracking branch with new commits from the local branch, even when rebasing against the branch.

A (possible) better way to sync a feature branch when using the `rebase` sync-feature-strategy is:

```fish
git rebase parent
git push --force-with-lease --force-if-includes
```

If the last operation goes through: the tracking branch had no changes. No need to pull updates from it. This branch is now fully synced. If the last operation fails: the tracking branch contains additional changes that aren't included in the local branch yet. In this case Git Town would need to pull those new commits into the local branch and push again:

```fish
git rebase parent
git push --force-with-lease --force-if-includes
```

### implementation

- [x] try this out manually
- [x] add `--force-if-includes` to all calls of `git push --force-with-lease`
- [x] change the opcodes in the program to sync a feature branch using the `rebase` sync-feature-strategy

**Comment by kevgo** [comment]
Manual experimentation confirms that this seems to work properly.

- local changed, remote changed: correctly refuses the push, recommends git pull, after git pull the push works
- local changed, remote unchanged: correctly pushes locally amended commits to the unchanged remote
- local unchanged, remote changed: push correctly does not go through, recommends git pull, after git pull push is correctly a no-op
- local unchanged, remote unchanged: correct no-op
