### ISSUE TITLE
Support for multiple ship strategies

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3902]
Currently `git town ship` supports only one complex strategy: if a token is set, and the PR can be shipped via API, then ship via API, otherwise ship locally. With a new ship strategy coming in #3236 and #2441, it's time to bring the ship subsystem up to the level that the other parts of Git Town have now.

- [x] add a `ship-strategy` concept to the domain model
- [x] configuration option for the strategy to use for shipping
- [x] `api` ship strategy: ship via the API, exit with an error if that's not possible
- [x] `squash-merge` ship strategy: ship via a local squash-merge and then push
- [x] `ff` ship strategy: ship by fast-forwarding the feature branch onto the main branch locally and then pushing. This will work on GitHub. This is the new strategy for #3236.

**Comment by kevgo** [comment]
What should be the default behavior if there is no ship strategy defined? Possible answers:

- `nothing`: it returns an error message asking the user to specify a ship strategy
- `disabled`
- `api`: this is the safest option since it doesn't introduce something that the user might not want
